#
# Configuration
#
ECLIPSE_TAG="R4_16"

ECLIPSE_TOP="platform/eclipse.platform.releng.aggregator"
ECLIPSE_MODULES="
	jdt/eclipse.jdt
	jdt/eclipse.jdt.core
	jdt/eclipse.jdt.core.binaries
	jdt/eclipse.jdt.debug
	jdt/eclipse.jdt.ui
	pde/eclipse.pde.build
	pde/eclipse.pde.ui
	platform/eclipse.platform
	platform/eclipse.platform.common
	platform/eclipse.platform.debug
	platform/eclipse.platform.releng
	platform/eclipse.platform.resources
	platform/eclipse.platform.runtime
	platform/eclipse.platform.swt
	platform/eclipse.platform.swt.binaries
	platform/eclipse.platform.team
	platform/eclipse.platform.text
	platform/eclipse.platform.ua
	platform/eclipse.platform.ui
	platform/eclipse.platform.ui.tools
	equinox/rt.equinox.binaries
	equinox/rt.equinox.bundles
	equinox/rt.equinox.framework
	equinox/rt.equinox.p2"

PATCH_DIR="java-eclipse/files"
PATCHED_DIRS="
	eclipse-platform-parent
	eclipse.pde.build
	eclipse.pde.ui
	eclipse.platform.releng
	eclipse.platform.releng.tychoeclipsebuilder
	eclipse.platform.resources
	eclipse.platform.runtime
	eclipse.platform.swt
	eclipse.platform.swt.binaries
	eclipse.platform.team
	eclipse.platform.text
	eclipse.platform.ua
	eclipse.platform.ui
	rt.equinox.bundles
	rt.equinox.framework
	rt.equinox.p2
"
