# Created by: Jonathan Chen <jonc@chen.org.nz>
# $FreeBSD$

PORTNAME=   	eclipse
PORTVERSION=    4.6
CATEGORIES= 	java devel

MAINTAINER=		jonc@chen.org.nz

LICENSE=		EPL

BUILD_DEPENDS=	${LOCALBASE}/share/java/maven/bin/mvn:devel/maven
USE_GNOME=		gtk30

USE_JAVA=       yes
JAVA_VERSION=   1.8+

.include <bsd.port.mk>
