#!/bin/sh
#set -x
#
# Move sub-projects into the right place
#
ECLIPSE_TOP="eclipse.platform.releng.aggregator"
ECLIPSE_MODULES="
	eclipse.jdt
	eclipse.jdt.core
	eclipse.jdt.core.binaries
	eclipse.jdt.debug
	eclipse.jdt.ui
	eclipse.pde.build
	eclipse.pde.ui
	eclipse.platform
	eclipse.platform.common
	eclipse.platform.debug
	eclipse.platform.releng
	eclipse.platform.resources
	eclipse.platform.runtime
	eclipse.platform.swt
	eclipse.platform.swt.binaries
	eclipse.platform.team
	eclipse.platform.text
	eclipse.platform.ua
	eclipse.platform.ui
	eclipse.platform.ui.tools
	rt.equinox.binaries
	rt.equinox.bundles
	rt.equinox.framework
	rt.equinox.p2"

mv ${AGGR_MODULE}-${ECLIPSE_TAG} ${AGGR_MODULE}

for M in ${ECLIPSE_MODULES}
do
	MODULE=$(basename $M)
	SNAP="${MODULE}-${ECLIPSE_TAG}"
	SUBDIR="${AGGR_MODULE}/${MODULE}"
	ARCHIVE="distfiles/${SNAP}.tar.xz"

	if [ ! -r ${ARCHIVE} ]
	then
		echo "FATAL: ${ARCHIVE} not found"
		exit 1
	fi

	echo "INFO: Unpacking ${M}"
	rm -rf ${SUBDIR}
	tar xf ${ARCHIVE}
	mv ${SNAP} ${SUBDIR}
done
